jobs:
  include:
    - language: php
      php: '5.6'
      env: TEA_UTIL_ENV="php56"
    - language: php
      php: '7.0'
      env: TEA_UTIL_ENV="php70"
    - language: php
      php: '7.1'
      env: TEA_UTIL_ENV="php71"
    - language: php
      php: '7.2'
      env: TEA_UTIL_ENV="php72"
    - language: php
      php: '7.3'
      env: TEA_UTIL_ENV="php73"
    - language: csharp
      mono: none
      dist: xenial
      env: TEA_UTIL_ENV="csharp"
    - language: java
      jdk: openjdk8
      env: TEA_UTIL_ENV="java"
    - language: go
      go: 1.12.x
      env: TEA_UTIL_ENV="go"
    - language: node_js
      node_js: 12
      env: TEA_UTIL_ENV="ts"

script:
  - bash ut.sh ${TEA_UTIL_ENV}
